# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Push IMS Data Explorer Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Log in to GH Packages registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build Docker images
        shell: bash
        run: |
          docker build --platform linux/arm64 -t ghcr.io/${{ github.repository_owner }}/ims-data-explorer:1.0.0 .
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/arm64
#          load: true
#          tags: vc-fms/ims-data-explorer:1.0.0
#
      - name: Push to GH Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ims-data-explorer:1.0.0
